### ISSUE TITLE
Unknown reference type: 13/Generic

### ISSUE THREAD

**Issue by mkchoong** [CREBP/SRA#1]
I encountered the problem "Unknown reference type: 13/Generic. Please report this at https://github.com/hash-bang/RefLib/issues with a copy of your EndNote XML file if you believe this is in error"  when I am trying to upload my EndNote XML to CREBP SRA.

I can't attached my XML file here (only support PNG, GIF or JPG).

**Comment by hash-bang** [comment]
Thanks @mkchoong. I've updated the EndNote reference database in the RefLib library (fix https://github.com/hash-bang/RefLib/commit/b4114e46af1d01580a2f210b0a5bace4bb60b977).

This should now be working.

Please let me know if you see any more of these.
